/** 
 * This class 'InterfaceExample.java' was generated by RedDeer Code Generator. 
 * Selected options:
 *		Getter
 *		Setter
 *		Action method
 *		Generate static constants
 *		Include all wizard pages
 *		Allow inheriting (only, if are included all wizard pages)
 */ 
package examples;

import org.eclipse.reddeer.swt.impl.button.PushButton;
import org.eclipse.reddeer.jface.wizard.WizardDialog;
import org.eclipse.reddeer.swt.impl.button.CheckBox;
import org.eclipse.reddeer.swt.impl.button.RadioButton;
import org.eclipse.reddeer.swt.impl.text.LabeledText;
import org.eclipse.reddeer.swt.impl.shell.DefaultShell;

public class InterfaceCodeGenClassExample extends WizardDialog {

	// Generated class methods (43)
	public void clickRemoveBTN() {
		new PushButton("Remove").click();
	}

	public void clickAddBTN() {
		new PushButton("Add...").click();
	}

	public void clickBrowseBTN() {
		new PushButton("Browse...").click();
	}

	public CheckBox getGenerateCommentsCHB() {
		return new CheckBox("Generate comments");
	}

	public String getTextGenerateComments() {
		return new CheckBox("Generate comments").getText();
	}

	public PushButton getRemoveBTN() {
		return new PushButton("Remove");
	}

	public String getTextRemove() {
		return new PushButton("Remove").getText();
	}

	public PushButton getAddBTN() {
		return new PushButton("Add...");
	}

	public String getTextAdd() {
		return new PushButton("Add...").getText();
	}

	public RadioButton getProtectedRDB() {
		return new RadioButton("protected");
	}

	public String getTextProtected() {
		return new RadioButton("protected").getText();
	}

	public RadioButton getPrivateRDB() {
		return new RadioButton("private");
	}

	public String getTextPrivate() {
		return new RadioButton("private").getText();
	}

	public RadioButton getPackageRDB() {
		return new RadioButton("package");
	}

	public String getTextPackage() {
		return new RadioButton("package").getText();
	}

	public RadioButton getPublicRDB() {
		return new RadioButton("public");
	}

	public String getTextPublic() {
		return new RadioButton("public").getText();
	}

	public LabeledText getNameTXT() {
		return new LabeledText("Name:");
	}

	public String getTextName() {
		return new LabeledText("Name:").getText();
	}

	public PushButton getBrowseBTN() {
		return new PushButton("Browse...");
	}

	public String getTextBrowse() {
		return new PushButton("Browse...").getText();
	}

	public CheckBox getEnclosingTypeCHB() {
		return new CheckBox("Enclosing type:");
	}

	public String getTextEnclosingType() {
		return new CheckBox("Enclosing type:").getText();
	}

	public LabeledText getPackageTXT() {
		return new LabeledText("Package:");
	}

	public LabeledText getSourceFolderTXT() {
		return new LabeledText("Source folder:");
	}

	public String getTextSourceFolder() {
		return new LabeledText("Source folder:").getText();
	}

	public DefaultShell getShellNewJavaInterface() {
		return new DefaultShell("New Java Interface");
	}

	public String getTextNewJavaInterface() {
		return new DefaultShell("New Java Interface").getText();
	}

	public boolean isCheckedGenerateCommentsCHB() {
		return new CheckBox("Generate comments").isChecked();
	}

	public boolean isSelectedProtectedRDB() {
		return new RadioButton("protected").isSelected();
	}

	public boolean isSelectedPrivateRDB() {
		return new RadioButton("private").isSelected();
	}

	public boolean isSelectedPackageRDB() {
		return new RadioButton("package").isSelected();
	}

	public boolean isSelectedPublicRDB() {
		return new RadioButton("public").isSelected();
	}

	public boolean isCheckedEnclosingTypeCHB() {
		return new CheckBox("Enclosing type:").isChecked();
	}

	public void setTextName(String str) {
		new LabeledText("Name:").setText(str);
	}

	public void setTextPackage(String str) {
		new LabeledText("Package:").setText(str);
	}

	public void setTextSourceFolder(String str) {
		new LabeledText("Source folder:").setText(str);
	}

	public void toggleGenerateCommentsCHB(boolean choice) {
		new CheckBox("Generate comments").toggle(choice);
	}

	public void toggleProtectedRDB(boolean choice) {
		new RadioButton("protected").toggle(choice);
	}

	public void togglePrivateRDB(boolean choice) {
		new RadioButton("private").toggle(choice);
	}

	public void togglePackageRDB(boolean choice) {
		new RadioButton("package").toggle(choice);
	}

	public void togglePublicRDB(boolean choice) {
		new RadioButton("public").toggle(choice);
	}

	public void toggleEnclosingTypeCHB(boolean choice) {
		new CheckBox("Enclosing type:").toggle(choice);
	}

}